add_grocery:
  fields:
    name:
      required: true
      selector:
        text:
    quantity:
      default: 1
      selector:
        number:
    list_id:
      default: default
      selector:
        text:
    store:
      selector:
        text:
    assignee_id:
      selector:
        text:
complete_chore:
  fields:
    chore_id:
      required: true
      selector:
        text:
sync_calendar:
